plugins {
  id 'java'
  id 'war'
  id 'checkstyle'
  id 'pmd'
    id 'org.jetbrains.kotlin.jvm' version '2.4.20'
    id "org.jetbrains.kotlin.plugin.jpa" version '2.4.20'
}

group = 'com.github.vodobryshkin.is-lab1'
version = '1.0-SNAPSHOT'

repositories {
  mavenCentral()
}

ext {
  junitVersion = '5.14.4'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

checkstyle {
  toolVersion = '14.1.0'
  configFile = file('config/checkstyle/checkstyle.xml')

  ignoreFailures = false
  showViolations = true
}

pmd {
  consoleOutput = true
  toolVersion = '7.16.0'
  rulesMinimumPriority = 5

  ruleSetFiles = files('config/pmd/pmd.xml')
  ruleSets = []
}

tasks.withType(Pmd).configureEach {
  reports {
    html.required = true
    xml.required = true
  }
}

dependencies {
  compileOnly 'jakarta.platform:jakarta.jakartaee-web-api:10.0.0'

  testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
  testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
  useJUnitPlatform()
}