import "./enum/Color.tsp";
import "./enum/Country.tsp";
import "./enum/OrganizationType.tsp";
import "./enum/Position.tsp";
import "./enum/Status.tsp";

import "./model/AddressFields.tsp";
import "./model/CoordinatesFields.tsp";
import "./model/LocationFields.tsp";
import "./model/OrganizationFields.tsp";
import "./model/PersonFields.tsp";
import "./model/WorkerFields.tsp";

namespace WorkersApi.Domain;